global:
  resolve_timeout: 5m

route:
  receiver: 'default-receiver'

receivers:
  - name: 'default-receiver'
    email_configs:
      - to: 'test@example.com'
        from: 'alertmanager@example.com'
        smarthost: 'host.docker.internal:1025'
        send_resolved: true
        require_tls: false