services:
  chat-mvc:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: chat-mvc
    privileged: true
    ports:
      - "8080:8080"
    networks:
      - chat-net
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
        reservations:
          cpus: "0.5"
          memory: 512M

networks:
  chat-net:
    name: chat-net
    driver: bridge