global:
  scrape_interval: 5s

rule_files:
  - "alert_rules.yml"

scrape_configs:
  - job_name: 'chat-server'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['host.docker.internal:8080']