services:
  chat-prometheus:
    image: prom/prometheus
    container_name: chat-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - chat-net

  chat-grafana:
    image: grafana/grafana
    container_name: chat-grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/etc/grafana/dashboards
    networks:
      - chat-net


networks:
  chat-net:
    external: true